# Generated by Django 4.0.6 on 2022-07-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_grocery_price_alter_grocery_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='category',
            field=models.CharField(choices=[], default='blank', max_length=200),
        ),
    ]
