# Generated by Django 4.0.6 on 2022-07-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_grocery_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='category',
            field=models.CharField(choices=[('🍓Fruits', 'Fruits'), ('🥒Vegetables', 'Vegetables'), ('🥫Canned Goods', 'Canned Goods'), ('🥛Dairy', 'Dairy'), ('🥩Meat', 'Meat'), ('🐟Fish & Seafood', 'Seafood')], default='blank', max_length=200),
        ),
    ]
