# Generated by Django 4.0.6 on 2022-07-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_grocery_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocery',
            options={'ordering': ['-created_on'], 'verbose_name': 'Grocery', 'verbose_name_plural': 'Groceries'},
        ),
    ]
