# Generated by Django 4.0.6 on 2022-07-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_grocery_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='category',
            field=models.CharField(blank=True, choices=[('🍓Fruits', 'Fruits'), ('🥒Vegetables', 'Vegetables'), ('🥫Canned Goods', 'Canned Goods'), ('🥛Dairy', 'Dairy'), ('🥩Meat', 'Meat'), ('🐟Fish & Seafood', 'Seafood'), ('🧂Condiments and Spices', 'Condiments'), ('🍟Snacks', 'Snacks'), ('🍞Baked Goods', 'Baked Goods'), ('🧃Beverages', 'Beverages'), ('🍝Pasta', 'Pasta And Rice'), ('🥚Baking Products', 'Baking Products'), ('🍗Frozen Food', 'Frozen Food'), ('🚼Baby Items', 'Baby Items'), ('🐕Pet Care', 'Pet Care'), ('Miscellaneous', 'Miscellaneous')], default='blank', max_length=200),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='price',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
