# Generated by Django 4.0.6 on 2022-07-19 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_groceryitem_alter_grocery_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='quantity',
        ),
    ]
