# Generated by Django 4.0.6 on 2022-07-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_groceryitem_grocery_price_grocery_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
